service: data-pusher-v1

provider:
  name: aws
  runtime: python3.8
  region: us-east-1
  memorySize: 512
  timeout: 30

plugins:
  - serverless-python-requirements
  - serverless-dotenv-plugin

custom:
  pythonRequirements:
    dockerizePip: true
  dotenv:
    path: .env

functions:
  daily-scheduler:
    handler: queues.daily_scheduler_lambda.handler
    package:
      include:
        - repositories/user_token_repository.py
        - services/user_token_service.py
        - requirements.txt
    tracing: "true"
    events:
      - eventBridge:
          schedule: cron(1 0 * * ? *)

  update-user-token:
    handler: queues.update_user_token_lambda.handler
    package:
      include:
        - repositories/user_token_repository.py
        - services/user_token_service.py
        - requirements.txt
    tracing: "true"
    events:
      - sns:
          topicName: user-token-topic
          displayName: Update User Token Lambda
          filterPolicy:
            event_type:
              - update-token-balance